[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "vis-tool2"
dynamic = ["version"]
description = "Visual Tool for Retico"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.3",
    "flask-cors>=6.0.2",
    "flask-socketio>=5.6.1",
]
authors = [
    {name = "Jason Do"},
]
license = { file = "LICENSE" }
keywords = ["real-time", "retico", "visual", "tool"]

[tool.setuptools.packages.find]
include = ["backend*"]